### ISSUE TITLE
conversations 1.13.1 blocking of contacts doesn't work

### ISSUE THREAD

**Issue by mdkuser** [siacs/Conversations#1921]
#### General information

* **Version:**  1.13.1
* **Device:** Moto G2 4G 
* **Android Version:** Android 6.0 Stock
* **Server name:** jabber.de
* **Server software:** prosody 0.9
* **Installed server modules:** Stream Managment, CSI, Blocking command, HTTP upload, Carbons
* **Conversations source:** F-Droid

#### Steps to reproduce

1. block a contact via conversations
2. send a message from the blocked contact to yourself

#### Expected result

Message should not have been delivered from blocked contacts

But  conversations just displays a hint about this user is blocked and the message from the blocked contact gets delivered anyway.

Note: 

I also tested to block same contact using pidgin and then try to send a test message from blocked contact to myself give expected result in pidgin, message not delivered. So I think this is not a server side issue.
Conversation failed to block users using a different server that is running prosody with blocking command (mod_privacy and mod_blocking) too.

**Comment by iNPUTmice** [comment]
Is the hint that the contact is blocked persistent across restarts of Conversations?

**Comment by iNPUTmice** [comment]
Just tested this on jabber.de - Doesn't work for me either. But it is persistent across restarts and it even shows up in the block list. The block list gets reloaded from the server on every login. Which means the servers knows we are trying to block a user but simply doesn't.

**Comment by iNPUTmice** [comment]
Maybe mod_privacy isn't loaded? https://modules.prosody.im/mod_blocking.html

**Comment by mdkuser** [comment]
"Conversation failed to block users using a different server that is running prosody with blocking command (mod_privacy and mod_blocking) too."

mod_privacy AND mod_blocking are loaded for sure on the differnt server

and regarding jabber.de, since it works with pidgin, I am quite sure the server is supporting blocking, it seems a client issue since it works with non conversation client on jabber.de and conversations fails for two diffent servers I tested, both servers work for pidgin.

Also side effect, revoking presens (online status) allowance from a roaster contact sometimes doesn't take effect, the contact still sees me online even if permissions to see online status have been revoked and conversations contact details shows the two checkboxes as unchecked...

**Comment by mdkuser** [comment]
Please do not close this issue, you are ssaying you reproduced this issue and I mentioned that the case is not only with jabber.de but also with others and that pidgin works with jabber.de as well as with the other server, so this really looks like a issue on conversations not on the server (or why it's working in pidgin?)

**Comment by iNPUTmice** [comment]
Maybe Pidgin is not using the Blocking Command.

Conversations is issuing the IQ request. The server is confirming it and is even reporting the blocked JID back to use when you restart Conversations. (You can check this yourself. If the message 'Contact is blocked' is still showing after a restart you'll know that the server knows we are trying to block the user. Conversations doesn't persist this information across restarts.)

It's working fine on my ejabberd based server.

This is strong evidence for me that this is in fact a server issue. If you can reproduce this on other prosody based servers this might be a Prosody issue.

**Comment by iNPUTmice** [comment]
If you have administrative access to the server a highly speculative guess is that https://hg.prosody.im/prosody-modules/file/tip/mod_blocking/mod_blocking.lua#l37 ff should be true.

(And of course you have to re-add the entry before trying it)

**Comment by mdkuser** [comment]
I tested this modifying mod_blocking line 37-40 from false to true and vice versa it's not solving the issue with conversations still happily delivers messages from blocked users!
However using the unmodified mod_blocking with gajim results in propper blocking same as previous pidgin tests.
Here are the details of my testing which I believe shows the problem is on conversations side:

Conversation started:
no privacy file created under /var/lib/prosody/<DOMAIN>/privacy/

Gajim started:
privacy file with empty blocklist is created under /var/lib/prosody/<DOMAIN>/privacy/

A) blocking contact using gajim:

A1) in Gajim: 

Messages from this contact are blocked in gajim
the contact is shown as blocked in roaster
The blocked user no longer sees my online status

A2) In Coversations: 

Messages are still recieved, conversations just loggs a hint about this user is beeing blocked
The contact is shown as blocked in roaster
The blocked user no longer sees my online status

B) blocking contact using conversations:

B1) in Gajim: 

Messages from this contact are blocked in gajim
The contact is NOT shown as blocked in roaster
The blocked user no longer sees my online status

B2) In Coversations: 

Messages are still recieved, conversations just loggs a hint about this user is beeing blocked
The contact is shown as blocked
The blocked user no longer sees my online status


C) Difference of the privacy list created by gajim (<) and conversations (>)

7c7
< 					["message"] = true;
---
> 					["message"] = false;
10,13d9
< 					["presence-out"] = true;
< 					["order"] = 1;
< 					["presence-in"] = false;
< 					["iq"] = true;
14a11,14
> 					["presence-out"] = false;
> 					["presence-in"] = false;
> 					["iq"] = false;
> 					["order"] = 0;


Changing the line 35-40 in mod_blocking doesn't solves the issue

Please reopen this issue!

**Comment by iNPUTmice** [comment]
The diff you posted is evidence to me that you didn't reload the module after making the change. The suggested change in code would lead to exactly this kind of change.

However you saying that.

> blocking a contact using gajim: [...] Messages are still recieved, conversations just loggs a hint about this user is beeing blocked

could indicate that something else is wrong here on the server side.

To make this clear once again. What you are saying here is:

> blocking a contact using gajim. [...] conversations just loggs a hint about this user is beeing blocked

so the server **knows** we want to block the contact.

> Messages are still recieved,

but **doesn't**.

I'm really not sure what more do you need to proof that this is a server bug.

Full disclosure: While looking at the Conversations code yesterday I noticed that Conversations wasn't responding to block list pushes. I fixed that on my side - and I will push that fix today - but it didn't change anything.

**Comment by mdkuser** [comment]
I did reload the modules after making changes, but making changes did not fixed it for conversations but broke it in gajim, therefore I reverted the changes back and used the unmodified vanilla mod_blocking from prosody repo again and the diff I was posting is a diff the shows that after the vanilla mod is reloaded, the blocklist that gajim creates differs from the one that prosody creates. Shouldn't that be identically on both clients?

Also I wrote that with vanilla mod_blocking the blockin in gajim works well even if blocking is done via conversations but conversations ignores the blocking no matter if blocked using gajim or blocked using conversations.

Please try the following:

1) register a jabber.de account and activate in conversations 
2) register a jabber account on a different server and activate in converstaions as a second account
3) add user@jabber.de as contakt to user2@otherjabber.tld and vice versa
4) block user2@otherjabber.tld using conversations
5) try to send messages from blocked user2@otherjabber.tld to user@jabber.de

You get the results I just mentioned.

6) now log out your jabber.de account in conversations and logon with your jabber.de account in gajim
7) try to send a mesage from blocked user try to send messages from blocked user2@otherjabber.tld to user@jabber.de

Although gajim is not shown the user as blocked it blocks incoming messages, conversations stil  happyly delivers messages from blocked users

Notze: if you do the blocking using gajim, gajim shows the contakt as blockes (crossed out) and blocks messages from this user, converstaions is also tagging the gajim blocked user als blocked but delivers messages...

This behaviour plus the fact that with unmodified mod_blocking (and the mod is active) conversations creates different blocking list that gajim does is IMHO an indicator, that theres something wrong in how conversations handles thos blocklists...

**Comment by mdkuser** [comment]
I should mention, that message carboons are anable on both sides the jabber.de and the otherjabber.tld

**Comment by iNPUTmice** [comment]
> the diff I was posting is a diff it shows after the vanilla mod has been reloaded

I know. You should have made the diff with the modified mod_blocking. (Remember that you have to block the contact again)

Anyway this discussion doesn't lead to anything since you are clearly not listing to my arguments.

I have an account on jabber.de and I'm getting the results. But your conclusion is wrong. If you want to know read what I said earlier.

**Comment by mdkuser** [comment]
Are you saying that now conversations is blocking contacts on your jabber.de account?

Modifying the mod_blocking just resulted in the presence info was still shown after blocking and of course I did reload the mod and unblocked and reblocked the contact again and loggout out and in again.

Yesterday you was confirming you get same results with jabber.de in conversations as I reported, now you are saying it's working for you?
Jabber.de did not changed mod_blocking mod_block_lists so if you get different results ysterday and today this is odd.

**Comment by mdkuser** [comment]
No offense, but if this is a server bug, how do you explain the fact that the blocking works correctly in two major desktop clients but not in conversations?

**Comment by mwild1** [comment]
Both Gajim and Pidgin have XEP-0016 (privacy lists) implementations. Without XML logs from those clients, we can't be sure they are using XEP-0191 (Blocking). That's one possible explanation.

**Comment by mdkuser** [comment]
Well, ok it seems like a server issue as final testing with mod_blocklists on 0.10 prosody works correctly with conversations. So maybe all the other clients was doing fallback to xep-0016.
Will have to file a bug report with prosody.
