### ISSUE TITLE
Some messages doesn't arrive

### ISSUE THREAD

**Issue by heipa0** [siacs/Conversations#2962]
Hello,

I am writing a lot of messages with a friend who lives in an area with a poor internet connection.

Sometimes messages I send to her will not arrive. See attached pictures for an example. It doesn't happen very often (maybe 1 of 200 messages) but it is still very annoying that the message delivery is not reliable.

If there is anything I can do to help solving this issue please let me know.

We both using the newest version of Conversation (2.1.0) from the Play Store but it also happened with previous versions. We both use the server jabber.at and encrypt messages with OMEMO.

Thanks

![messagelost](https://user-images.githubusercontent.com/35292661/38728006-27dccecc-3f41-11e8-9c02-dbd2e16581bf.png)

**Comment by SoyaLeaf** [comment]
Hi, I feel this depends on the server instead of the client.

**Comment by heipa0** [comment]
Well... I have no idea if its the fault of the server or the app. Is there a log or anything I can check?

**Comment by iNPUTmice** [comment]
Make sure you have activated MAM. Go to account details; select Archiving Preferences from the overflow menu and make sure it is set to Always.

**Comment by TntDestroyer** [comment]
Be thankful you aren't conversing with our ios cousins using chatsecure

https://github.com/ChatSecure/ChatSecure-iOS/issues/770

(I do, but problematically)

**Comment by heipa0** [comment]
@TntDestroyer I don't think the issues are related as my message doesn't arrive at all.

@iNPUTmice The Archiving Preferences were already set to Always on both devices.

**Comment by philfry** [comment]
that's pretty funny. As soon as I installed chatsecure on an ipad, both conversation and gajim stopped receiving omemo encrypted messages – only chatsecure got them.
Archiving preferences didn't change, it's et to "always" on all devices.

**Comment by dholl** [comment]
Me too.  I'm not sure of the underlying cause yet, but my other contacts do not receive messages that I send using OMEMO.  If I switch to unencrypted, then they receive just fine.

This is happening with contacts using either ChatSecure-iOS or Conversations.

My wife is using Conversations, and I also do not receive her messages either, unless she also switches to Unencrypted instead of OMEMO.

Communication was working just fine last week, but I'm not sure if the current failures are due to updates in Conversations or the automated updates I cron-scripted on my system.

Two of my friends using ChatSecure-iOS through my system are still able to chat just fine between themselves.

I'm especially alarmed that my wife and I (both on Conversations) are having difficulty with each other.  We both have "Send presence updates" and "Receive presence updates" marked for each other on our phones (as well as for our other contacts), and the "Server info" shows everything as available on both phones as well:
<img width="396" alt="screenshot_2018-04-21-16-03-47" src="https://user-images.githubusercontent.com/4298582/39089536-220e089c-457e-11e8-862a-108576648847.png">

As a server test, I re-ran the ```ComplianceTester-0.2.3``` and get passing marks in all areas:
```
Use compliance suite 'Advanced Server Core Compliance Suite' to test ad5ey.net

running XEP-0115: Entity Capabilities…		PASSED
running XEP-0163: Personal Eventing Protocol…		PASSED
passed 2/2

Advanced Server Core Compliance Suite: PASSED


Use compliance suite 'Advanced Server IM Compliance Suite' to test ad5ey.net

running XEP-0115: Entity Capabilities…		PASSED
running XEP-0163: Personal Eventing Protocol…		PASSED
running Roster Versioning…		PASSED
running XEP-0280: Message Carbons…		PASSED
running XEP-0191: Blocking Command…		PASSED
running XEP-0045: Multi-User Chat…		PASSED
running XEP-0198: Stream Management…		PASSED
running XEP-0313: Message Archive Management…		PASSED
passed 8/8

Advanced Server IM Compliance Suite: PASSED


Use compliance suite 'Advanced Server Mobile Compliance Suite' to test ad5ey.net

running XEP-0115: Entity Capabilities…		PASSED
running XEP-0163: Personal Eventing Protocol…		PASSED
running XEP-0198: Stream Management…		PASSED
running XEP-0352: Client State Indication…		PASSED
running XEP-0357: Push Notifications…		PASSED
passed 5/5

Advanced Server Mobile Compliance Suite: PASSED


Use compliance suite 'Conversations Compliance Suite' to test ad5ey.net

Server is Prosody 0.10.0
running XEP-0115: Entity Capabilities…		PASSED
running XEP-0163: Personal Eventing Protocol…		PASSED
running Roster Versioning…		PASSED
running XEP-0280: Message Carbons…		PASSED
running XEP-0191: Blocking Command…		PASSED
running XEP-0045: Multi-User Chat…		PASSED
running XEP-0198: Stream Management…		PASSED
running XEP-0313: Message Archive Management…		PASSED
running XEP-0352: Client State Indication…		PASSED
running XEP-0363: HTTP File Upload…		PASSED
running XEP-0065: SOCKS5 Bytestreams (Proxy)…		PASSED
running XEP-0357: Push Notifications…		PASSED
running XEP-0368: SRV records for XMPP over TLS…		PASSED
running XEP-0384: OMEMO Encryption…		PASSED
running XEP-0313: Message Archive Management (MUC)…		PASSED
passed 15/15

Conversations Compliance Suite: PASSED
```

@iNPUTmice - Would you have any tips on what diagnostics I should pursue?

I'm currently running Prosody 0.10.0 (Debian 0.10.0-1), and I've enabled debug messages in prosody.log

**Comment by dholl** [comment]
Update:  I fixed my inability to chat with my ChatSecure contacts by using "Delete OMEMO identities" under "Expert settings" on my phone.  I'll check with my Conversations contacts tomorrow...

**Comment by heipa0** [comment]
Back to the original issue...

I installed Gajim on the PC of my friend. After she didn't get a message I asked her to check Gajim. There the message arrived.
So it seems it only affects Conversations. :/

Again, if there is anything I can do to help solving the issue please let me know.

Thanks

**Comment by cfabio** [comment]
I think I am having the same issue.
I had `mod_mam` enabled but `default` option set to `never` in Ejabberd (version 18.04) because `mod_stream_mgmt` `resend_on_timeout: true` option usually was enough and handled sudden disconnections well.
It isn't the case anymore it seems, not sure if the culprit is Conversations or Ejabberd tho.
I would prefer not having to store anything on the server but still I don't see any better solution right now.

**Comment by whitetornado** [comment]
here also one. We dont store anything but still missing some messages as the topic starter sketch.

Can mobile internet (3G) vs WiFi a issue?
--

**Comment by iNPUTmice** [comment]
Conversations 2.3.9 will display 'unable to decrypt' warnings and will also attempt to self heal broken sessions. Both features require your server to support `mam:2`.
