### ISSUE TITLE
Duplicate messages when using stream management

### ISSUE THREAD

**Issue by singpolyma** [siacs/Conversations#879]
I enabled mod_smacks on my prosody, and now users with Conversations sometimes get duplicate messages when they reconnect.  I expect that these are stanzas that got delivered right before the network cut and so the ack never got sent up to the server.  It seems like Conversations should be able to detect this case (won't the stanza ids be the same?) and filter them out.

**Comment by iNPUTmice** [comment]
this isn't how sm works. the server won't just resend all stanzas from the last ack but on resume the client tells the server the last sequence number.
maybe what you are seeing are the effects of MAM or muc history.
filtering messages by id isn't always possible because a) messages are not required to have ids b) those ids don't have to be uuids. (conversations tries to do that when ever possible and where necessary. (muc, mam)
I by the way have never seen this happening. except with mam and muc in some scenarios. I have also seen some weird behavior with spectrum. but in those cases the duplicate messages arrived at my desktop as well and thus could not have been a result of failing sm

**Comment by singpolyma** [comment]
Don't have MAM right now, and the conversation isn't a MUC.  The only reason I thought of sm is that it just started happening and I enabled sm yesterday and haven't made any other changes.  I do also have carbons, but those have been on for some time.  I will try to investigate more when I get time.

**Comment by singpolyma** [comment]
Is there a good way to get an XML log file generated of stanzas in/out from Conversations for later analysis so I can debug this?

**Comment by SamWhited** [comment]
I see this behavior fairly frequently; I haven't had a chance to triage yet though. Mostly (maybe exclusively) with muc for me.

**Comment by singpolyma** [comment]
@SamWhited if yours is with MUC do you think it is sm related?  This is definitely with a 1:1

**Comment by SamWhited** [comment]
On January 13, 2015 2:00:18 PM EST, Stephen Paul Weber <notifications@github.com> wrote:
>@SamWhited if yours is with MUC do you think it is sm related?  This is
>definitely with a 1:1

If I notice it again I'll turn SM off and let you know.

**Comment by singpolyma** [comment]
@SamWhited I just disabled my SM because it was getting too much.  We'll see if the dupes go away again.  What is your server set up?  Is it prosody?  What version?  What mod_smacks version?  Any other community (non-core) modules?  Would be interesting for me to compare to mine, if you're not seeing this issue as much.  Same questions for @iNPUTmice

**Comment by SamWhited** [comment]
@singpolyma I'm on ejabberd 14.12, stream management on, only using core modules.

**Comment by devurandom** [comment]
I experience the same. Sometimes I receive the same messages again and again, so I end up with a dozen or so copies. I have SM and MAM enabled on my Prosody 0.10_pre (6224:2f709bc35575) server.

The time shown in the UI seems to be the received-time, as I guess from messages that are duplicated with more distance in time, but Conversation sorts messages by sent-time? Because duplicate messages are often shown like this: 1,1,1,1,1,1,2,2,2,2,2,2

**Comment by singpolyma** [comment]
@devurandom do you have mod_carbons as well?

**Comment by devurandom** [comment]
Yes

**Comment by singpolyma** [comment]
I wonder if carbons is interacting with smacks in a stupid way... haven't had time yet to test this idea.

**Comment by the-solipsist** [comment]
I too have seen this issue fairly frequently (though, I must admit, I haven't experienced it in around a fortnight or more).  I have Prosody 0.9.7, and mod_smacks and mod_carbons and mod_carbons_copies enabled, among others.

**Comment by devurandom** [comment]
More information:
* It never happens for sent messages, only for incoming
* It can happen hours after the original message was received, with good internet connectivity in the meantime
* It always affects the last messages received, never those in the middle of a conversation
* It can affect a group of messages (say 3 in a row)

This time it was like this:
* I was chatting on the computer, my phone received carbons – I heard the message sounds, but did not interact with the phone
* The conversation ended, I had a brief look at my phone and then did not interact with it any further
* Several hours later I looked at the phone again, having received some duplicate messages
* Several minutes or maybe an hour after that I again received duplicate messages of said conversation
* I was on wifi for the whole time, so the connection should have been stable

**Comment by devurandom** [comment]
Another instance of this issue:
* I had a conversation on my computer and ended it by shutting the machine down
* I received a last message from above conversation on the phone and read it there
* I kept receiving the message in the manner described above (2-3 times over the course of a few hours)
* When I started another computer, I received the message there, once
* I received no further copies on any of my machines

Thus I conclude this case seems to be linked to offline messages.

**Comment by vext01** [comment]
I enabled mod_smacks in prosody recently and have been receiving duplicate messages. Both parties are using conversations, and we are sending normal messages (not in a MUC or anything).

**Comment by flatman** [comment]
I'm facing the same problem with Prosody and mod_smacks. No MUC or carbons.

**Comment by morlix** [comment]
We have exactly the same issue. We have prosody 0.9.7 and 0.9.4 on another server.
Both servers have mod_smacks and mod_carbons enabled.

We never had such an issue with MUC only with "normal" chats.

I anyone of the devs need an account to verify this, you can create an account at jabber.ipfire.org.

We didn't have this issue with other xmpp clients like ChatSecure.

**Comment by vext01** [comment]
Hrm, this is becoming a problem. Can anyone suggest an alternative android client with a nice UI, carbons and smacks support?

**Comment by iNPUTmice** [comment]
I did some digging...

It seems like with recent prosody versions with every resume the stanza count of Conversations falls one behind prosodys stanza count. Meaning the first resume is fine. The second resume will give us one more stanza, the third resume two more, the forth three and so forth. Depending on the situation (whether we received only messages or other stanzas as well) that will result in duplicate messages. 

those are the facts. now come the wild speculations.

at this point I'm fairly certain that my stanza count (I'm counting every iq, presence and message) is correct. I reread my code did some debugging here and there.

a wild guess could be that prosody counts the resumed element as stanza?

I'm not seeing the behavior with 'older' versions of prosody. (I don't know exactly how old) And I haven't anyone complain about ejabberd.

@Zash

@vext01 the only other client a know of that supports SM is yaxim. Feel free to check this out and report back if you experience similar problems. That could help us narrow don't whether this is a server or a client problem.

**Comment by iNPUTmice** [comment]
I just very quickly did some tests with yaxim myself. I managed to produce duplicate messages once but couldn't reliably reproduce the results. (Staging this is actually a bit difficult because first of you have to produce a number of resumes to let the count diverge enough and then make sure that $count last stanzas contain at least on real message (real meaning with body and not just some receipt stuff that won't show up in the UI)

I'd love to see someone try yaxim for real for a couple of hours / days to see if yaxim really suffers from the same problem.

**Comment by Zash** [comment]
@iNPUTmice Could you get us debug logs from when this happens?

**Comment by iNPUTmice** [comment]
@Zash unfortunately no. I haven't seen this with any of my servers... I just observed this with the jabber.ipfire.org @morlix linked earlier.

**Comment by iNPUTmice** [comment]
Woke up and tried to analyze the problem with a clear mind. I tried to eliminate as many non-message-with-body stanzas as possible. Left all the conference to get rid of some presence. Turned of message confirmation.

I'm now sure that this doesn't happen with siacs.eu (I was previously afraid that I just never noticed the effects because of all the presence packets I receive) it does how ever happen with jabber.ipfire.org (both open for registration in case someone's interested)

My test setup: Logged in with one siacs.eu and one jabber.ipfire.org account in Conversations. Send messages from my computer with the siacs.eu account to the ipfire account. With carbons enabled Conversations now receives the same amount of messages to each account. (carbon copies for the siacs.eu account and real messages for the ipfire account.)
if both accounts would show the same symptoms they both would receive the same duplicate messages. But they didn't. Only the ipfire account received duplicate messages.


Unfortunately I'm no longer a 100% sure that the count diverges by one at every resume. Might have been a coincident and there are might be other reasons for the count to diverge. But I'm still about 80% sure. (This is all still very hard to measure because a) I have no access to the ipfire server logs b) there is no way I can know/request the servers count.)

**Comment by iNPUTmice** [comment]
One more thing. I noticed that ipfire.org - if the latest stanzas are not messages - it will just resend the same iq stanza result multiple times.
````
02-08 09:42:43.851 D/conversations( 2634): daniel@jabber.ipfire.org catchup: <iq xmlns="jabber:client" id="v1919dudec" to="daniel@jabber.ipfire.org/phone" type="result"><delay from="jabber.ipfire.org" xmlns="urn:xmpp:delay" stamp="2015-02-08T08:30:20Z"/></iq>
02-08 09:42:43.857 D/conversations( 2634): daniel@jabber.ipfire.org/phonestanza number 53 received
02-08 09:42:43.859 D/conversations( 2634): daniel@jabber.ipfire.org catchup: <iq xmlns="jabber:client" id="v1919dudec" to="daniel@jabber.ipfire.org/phone" type="result"><delay from="jabber.ipfire.org" xmlns="urn:xmpp:delay" stamp="2015-02-08T08:30:20Z"/></iq>
02-08 09:42:43.865 D/conversations( 2634): daniel@jabber.ipfire.org/phonestanza number 54 received
02-08 09:42:43.866 D/conversations( 2634): daniel@jabber.ipfire.org catchup: <iq xmlns="jabber:client" id="v1919dudec" to="daniel@jabber.ipfire.org/phone" type="result"><delay from="jabber.ipfire.org" xmlns="urn:xmpp:delay" stamp="2015-02-08T08:30:20Z"/></iq>
02-08 09:42:43.875 D/conversations( 2634): daniel@jabber.ipfire.org/phonestanza number 55 received
02-08 09:42:43.877 D/conversations( 2634): daniel@jabber.ipfire.org catchup: <iq xmlns="jabber:client" id="v1919dudec" to="daniel@jabber.ipfire.org/phone" type="result"><delay from="jabber.ipfire.org" xmlns="urn:xmpp:delay" stamp="2015-02-08T08:30:20Z"/></iq>
` ``` 

There is something very weird going on... Either you haven't updated your prosody-modules in for ever or there is something wrong with the lua libraries?

**Comment by morlix** [comment]
Hi iNPUTmice,

if you could tell me from which timeframe you need the server logs, i can provide them to you.

Thanks in advance for your debugging.
I will provide tomorrow a list of all software version we currently use in our infrastructure, so maybe we could find something which might cause these issues.

Kind regards,

morlix

**Comment by iNPUTmice** [comment]
@morlix at this point I'm fairly certain that this bug is not caused by Conversations. Please try to replicate the bug yourself under controlled circumstances. Feel free to do tests with yaxim as well. (Or any other client that supports SM.) and then send your log and findings to the prosody guys.

**Comment by morlix** [comment]
Hmm after a short test with yaxim i can definitely say, that i get messages only repeated once with yaxim instead of multiple times with Conversations. 

I hope i find some more time to dig deeper into this. Meanwhile it would be great to know how you tested.

**Comment by iNPUTmice** [comment]
@morlix have a look at `processPacket` at https://github.com/siacs/Conversations/blob/development/src/main/java/eu/siacs/conversations/xmpp/XmppConnection.java#L387

you can log the variable `stanzasReceived` and the variable `element` with with `Log.d(Config.LOGTAG,"stanza #"+stanzasReceived+": "+element.toString());` or something similar. You can compare that with the debug log of prosody which logs their stanza count.

**Comment by vext01** [comment]
fwiw, I just received a duplicate on yaxim.

**Comment by morlix** [comment]
did you receive one duplicate or more than one? i only received one duplicate with yaxim but multiple (between 10 and 30) with Conversations.

**Comment by vext01** [comment]
In this case, it was just one duplicate received by yaxim. It was from a user sending a message using conversations to a server running prosody with smacks and carbons installed.

IIRC, I was surprised that I received messages out of sequence. IIRC: A, B, C, A.

In my experience, when I was running conversations I tended to recieve many consecutive duplicates, e.g.: A, B, C, C, C, C, C, C, ...  Sometimes as many as 10 consecutive duplicates.

That's not to say the same thing couldn't happen in yaxim, just I have not seen it.

**Comment by vext01** [comment]
I switched back to conversations yesterday and today received 19 identical messages in a row, 18 of which are duplicates.

**Comment by iNPUTmice** [comment]
I ran into massive problems once I enabled csi, filter_chatstates and throttle_presences on my own prosody. I received duplicate messages as well as empty message stanzas that only contain a delay element and nothing more which I'm pretty sure none of my contacts ever sent. Sometimes after a resume I even received messages that originally arrived prior to a previous resume. Ever since I disabled those again everything went back to normal.
Considering the fact @morlix server doesn't have csi I'm starting to suspect that there is a bug in prosody that gets triggered under some weird circumstances and is more likely to be triggered when there is csi involved.

**Comment by arty-name** [comment]
I have just hit that issue with Conversations+Yaxim connecting to Prosody+smacks+carbons (no MUC). The duplicates only appeared in Conversations, not in Yaxim. I saw something interesting on the logs though. When I saw a duplicate, there were these lines in the log: 

    Mar 02 17:47:07 c2s1945db0  debug   Received[c2s]: <message id='bef62cd8-e663-48af-9c69-5bab2926560b' type='chat' to='atregoubenko@gmail.com' from='me@arty.name/mobile.57som3rl5'>
    Mar 02 17:47:07 arty.name:carbons   debug   Sending carbon to me@arty.name/mobile
    Mar 02 17:47:07 c2s193af20  debug   #queue = 1
    Mar 02 17:47:07 arty.name:carbons   debug   Sending carbon to me@arty.name/yaxim.2A9BE380
    Mar 02 17:47:07 c2s17d65b0  debug   #queue = 1

However when I logged Conversations off and on again and sent a message, I got NO duplicate, and these lines in the log: 

    Mar 02 17:49:02 c2s1720930  debug   Received[c2s]: <message id='292615a3-7832-406a-9164-65d9950d65d3' type='chat' to='atregoubenko@gmail.com' from='me@arty.name/mobile'>
    Mar 02 17:49:02 arty.name:carbons   debug   Sending carbon to me@arty.name/yaxim.2A9BE380
    Mar 02 17:49:02 c2s17d65b0  debug   #queue = 1

I don't know low-level details of XMPP but I noticed that in the first case there's a `from='me@arty.name/mobile.57som3rl5'` which causes a carbon to `me@arty.name/mobile` (and a bug), and in the second case `from='me@arty.name/mobile'` doesn't cause a carbon to `me@arty.name/mobile` and there's no bug then.

Does this information help? Is this how it is supposed to be?

**Comment by iNPUTmice** [comment]
@arty-name are you on version 1.1.0?

**Comment by arty-name** [comment]
@iNPUTmice yes, I am using Conversations 1.1.0

**Comment by iNPUTmice** [comment]
Are you guys still experiencing this with 1.2.0?

**Comment by morlix** [comment]
Unfortunately yes. I also updated our prosody smacks module, but without luck...
If i got a little spare time i will also contact the prosody devs again to get this issue solved.

**Comment by BrianBlade** [comment]
I noticed that mod_smacks on Prosody sometimes for (yet) unknown reasons stops increasing the incoming stanza count. This causes the last messages to be resend every time the sender resumes a stream-management session.
Dont know if its related but in my case the receiver was connected with Conversations and psi (the latter does not support stream management afaik), carbons enabled. 
The frozen stanza count was visible in prosody's debug log.
Unsure what to conclude, as this was certainly a Prosody issue but above comments mention similar issues with ejabberd. 
Just thought this might perhaps help somebody to identify the root cause.

**Comment by vext01** [comment]
When I updated from prosody-0.9.4. to 0.9.7 my duplicate messages problem ceased.

**Comment by arty-name** [comment]
I was getting the problem with prosody 0.10 nightly

**Comment by mwild1** [comment]
@arty-name What nightly though? some 0.10 nightlies are older than 0.9.7.

**Comment by devurandom** [comment]
Same here. And I think I am still getting them sometimes. (running 0ef7ca5276a1)

**Comment by arty-name** [comment]
@mwild1 the nightly version was 1nightly110-1~trusty

**Comment by tannercollin** [comment]
I am getting this issue with Conversations 1.2.0 and Prosody changeset 6609:d2faaaca695d (Mar 27 2015) running Prosody community modules (from Google code) changeset 1642:a4a6b4be973a (Mar 31 2015) with the default modules enabled, plus mam, smacks, carbons, blocking, and csi.

I can reproduce this with 100% accuracy. To reproduce it I use the accounts tanner@ and test@ and do the following:
1. Turn airplane mode on
2. Use Conversations to send message A from tanner to test
(message A says "waiting...")
3. Use Gajim on computer to send message B from test to tanner
4. Use Gajim on computer to send message C from tanner to test
5. Turn airplane mode off
(messages B and C appear in Conversations, message A appears in Gajim, message A says "sending..." in Conversations forever)
6. Use Conversations to send messages D, E, F from tanner to test
(messages D, E, F appear in Gajim, messages A, D, E, F all say "sending..." in Conversations forever)
7. Turn airplane mode on
(messages A, D, E, F now all say "waiting...")
8. Turn airplane mode off
(messages A, D, E, F appear again in Gajim so now it looks like "ABCDEFADEF", messages A, D, E, F all say "sending..." in Conversations forever)

You can repeat steps 7 and 8 and send all the duplicates you want. When the phone is online, any new messages sent tanner to test also say "sending..." forever and become part of the duplicate cycle when steps 7 and 8 are repeated. This also happens automatically over time as the Conversations connects and disconnects (you can see it change from "sending..." to "waiting..." and back by itself). This doesn't stop; In the time I spent writing this, Gajim is saying I have 34 new messages.

Note that when a Gajim chat window is closed and reopened, the order of the messages changes from "...ADEFADEFADEF" to "...AAADDDEEEFFF".

I hope this helps. Feel free to ask me any questions.

**Comment by mwild1** [comment]
@tannercollin Wow, thanks for the detailed description! Any chance you could send a debug log for this to developers@prosody.im?

Unfortunately Conversations won't run on my phone, so unless I can get it working in the emulator I'm a bit stuck reproducing the issue myself.

It seems like there might be multiple issues at play here. I was helping @vext01 debug for a while, but he only had a single client on each side, he also didn't get the "The client says it handled..." messages. His issue was fixed by upgrading Prosody (your version includes the fix). So I'm expecting your logs might tell a different story to any of the logs I've received so far...

To anyone else encountering the issue, make sure you are running Prosody 0.9.5+ (but latest is always best), or a recent 0.10/trunk snapshot/nightly. Make sure prosody-modules is up to date, at least 1627:ad6694f7b13c from 2015-03-21.

**Comment by kriztan** [comment]
@mwild1 I'm using latest prosody trunk with the modules a4a6b4be973a from 2015-03-31. Smacks seems not working as expected. First, I thought it's a misconfiguration of ipv6, so I've disabled ipv6 but the problem still exists. Now I'm sure, it is smacks. Currently I'm using the latest smacks version before 2015-03-21 and it seems to work. 
Sending a message from conversations remains in the status `sending...` but the messages were delivered, sometimes with duplicates. If you are interested in the prosody logfiles, I can send you a mail.
To reproduce it, setup prosody trunk with the prosody modules ad6694f7b13c from 2015-03-21 and restart prosody. Now send a message to a user from wlan then switch of wlan and let the phone connect to a mobile network. Send another message to a contact, this message remains in status `sending...`. You can also try a vice versa, it's allways the same.

**Comment by mgansler** [comment]
I manually reverted the changes made in the commit on 2015-03-21 (https://code.google.com/p/prosody-modules/source/diff?spec=svnad6694f7b13c5a83fef7fcb1be9df71f9543fe71&r=ad6694f7b13c5a83fef7fcb1be9df71f9543fe71&format=side&path=/mod_smacks/mod_smacks.lua, line 318) because I had the same troubles with duplicated message (only, I did not receive any duplicates, but they were sent to my chat partners).

What I noticed was, that when I sent a message from Conversations 1.2.0 (and also 1.3.0-alpha), the status stayed at "sending". With the older Version of mod_smacks, the status changes to "just now" a few (mili-)seconds after hitting "send".

I am running prosody 0.9.8 and changeset:   1674:7f4c64cfed09 of the community modules, I have "compression", "pep", "smacks" and "carbons" enabled.
I run prosody inside my own docker container: https://registry.hub.docker.com/u/mgansler/prosody/

**Comment by incognico** [comment]
@mgansler So you don't get or send any duplicate messages and the status (sending, just now) is displayed correctly with the said commit reverted?

**Comment by mgansler** [comment]
Yes!

**Comment by mase76** [comment]
Mostly I get the same messages 8 times. I cannot say, if it is related to conversations,
because I have not found a client supporting stream management.
But when using a mod_smacks version from January, it seems to be much better,
but not fixed. This behaviour is very annoying. My Prosody version is 0.10 with mod_smacks,
mod_mam, mod_mam_archive, mod_csi, mod_throttle_presence, mod_carbons.
I disabled mod_mam_archive, mod_csi and mod_throttle_presence for testing, but it did
not help.
I saw this in the prosody log:
The client says it handled 2 new stanzas, but we only sent 0 :)

**Comment by astro** [comment]
I seem to be sending a lot of duplicate messages with Conversations 1.2.0 and Prosody 0.9 debd9a7be528 with the following plugins:
```lua
                "smacks";
                "carbons";
                "blocking";
                "mam";
                "mam_muc";
                "mam_adhoc";
                "csi";
```

Seems to happen whenever I switch networks.

**Comment by kriztan** [comment]
I've just noticed, that there were duplicates when user A writes a message to B, who is just restarting the phone. The message from A was sent twice to B, and this message is marked as successfully deliverd to user A.
I'm using prosody trunk 557 from 2015-04-26 with the current modules version c77e9522dc66 from 2015-04-25. In prosody the following third party modules were enabled:
auto_accept_subscriptions, block_registrations, blocking, carbons, csi, mam, mam_muc, pep_plus, register_web, server_contact_info, smacks, support_contact, throttle_presence, watchregistrations

**Comment by Natureshadow** [comment]
I am having the same issue with the same setup.

Sometimes, messages are sent again even when reconnecting after hours.

It does not happen with other clients.

It also affects MUC.

**Comment by mase76** [comment]
What other clients? I don't know any for android with mam, carbons and message streaming support.
The prosody devs say, that this is an conversations issue.
The conversations devs say, it is a prosody issue.
So how to solve?

**Comment by Natureshadow** [comment]
I do not see the issue with Gajim and all the features enabled.

However, I clearly see Conversations send <message> stanzas directly to the other party, so it clearly is a Conversations issue.

**Comment by iNPUTmice** [comment]
> Sometimes, messages are sent again even when reconnecting after hours.

are those messages that were marked as sent?

**Comment by Natureshadow** [comment]
That's a good question. I believe they are.

Are you thinking that maybe message receipts got lost and thus Conversatiosn resends them?

In any case, I see another issue. Quite often, mesages jsut say "Sending...", even long after they were delivered to the other party.

Maybe there really is an issue with message receipts rather than sm?

**Comment by iNPUTmice** [comment]
Conversations does not use message receipts to resend messages. The message state is being switched from sending to sent after the servers stream managment has acked the message. if you see sending even after the recepient has received your message that means the server doesn't ack your messages which indicates a problem in SM.

> The prosody devs say, that this is an conversations issue.

@mase76 when/where did they say that?

**Comment by mase76** [comment]
@iNPUTmice I already reported this issue via email with the prosody dev.

gajim or pidgin cannot have this issue, as they don't support message streaming.

How can we help to get rid of this very annoying issue?
Maybe you could provide some debug builds.
It does not matter if this is a server or client issue. We must
solve this together instead.

**Comment by iNPUTmice** [comment]
I'm happy to help. and I did so already as this thread shows. however I'm not experiencing the bug myself despite the fact that I am using prosody myself so my options are limited.

**Comment by mase76** [comment]
I can create a test account for you on my server.
-- 
gpg-id: ccdbc2cf
https://www.setho.org/people

**Comment by iNPUTmice** [comment]
bcdfdb9ccf4cdd4e875850bc45852eb14ed6faf1 introduces a config option to log Conversations’ stanza counts. This should make it visable if prosody stops incrementing stanza counts as @BrianBlade noticed:
> I noticed that mod_smacks on Prosody sometimes for (yet) unknown reasons stops increasing the incoming stanza count. This causes the last messages to be resend every time the sender resumes a stream-management session.

I think it will be important to differentiate between messages being *send* multiple times and messages being *received* multiple times.

with the debug option enabled Conversations should log something similiar to this after each message:

if you are missing the second line or that line gives you a different stanza number something is wrong.

````
D/conversations(11602): inputmice@siacs.eu: requesting ack for message stanza #16
D/conversations(11602): inputmice@siacs.eu: server acknowledged stanza #16
````

**Comment by iNPUTmice** [comment]
btw if you are unwilling to debug this yourself there is also the option of switching to ejabberd which doesn't seem to have those issues. I have no problem with prosody myself but the sm module in prosody is marked as unstable and so is the prosody version 0.10 which a lot of you seem to be using. stream managment in ejabberd on the other hand is available in the stable branch.

**Comment by deoren** [comment]
We started having this issue on our Prosody 0.10 installation as well recently. We were trying to troubleshoot lots of failed image deliveries, long wait times, etc by downgrading our Conversations version. We started at 1.2.0 and then went to 1.1.0 and then I _think_ finally to 1.0.0. After not really seeing any change we did a direct upgrade back to 1.2.0.

Not sure if that is in any way helpful or not or just muddies the water so to speak. We are also using the smacks module with a default 5 minute timeout setting. I'm specifically using 0.10 in order to gain the MAM functionality.

* https://code.google.com/p/prosody-modules/wiki/mod_mam
* https://code.google.com/p/prosody-modules/wiki/mod_mam_archive

When I noticed the duplication today it was first from a Pidgin client. I then checked Conversations on my Nexus 4 (Android 4.4.4) and saw them there as well. I checked the prosodyarchive table in the database and found them listed there as well.

The sender did not see the duplicate messages in the list on their end. They initially reported send errors and then reported that those notices were gone when they glanced again.

**Comment by deoren** [comment]
I reverted mod_smacks to `1635:b877b75eb973` on our installation to see if that helps. So far I'm not seeing the same behavior, but because I had to reboot Prosody to load the downgraded module it's too soon to say for sure.

**Comment by mase76** [comment]
I tried a mod_smacks version from January. Somewhat better, but not solved.

**Comment by Natureshadow** [comment]
The issue goes away with ejabberd 15.03 with all the modules enabled.

**Comment by mwild1** [comment]
@iNPUTmice Thanks for the new debug option. If anyone who is experiencing the issue can enable this and provide some insight, it will be really useful. Thanks!

**Comment by deoren** [comment]
@mwild1 I assume that if we capture debug output you're only interested if we are running the latest version of `mod_smacks`?

**Comment by deoren** [comment]
@iNPUTmice Is the debug option included with bcdfdb9 part of the 1.3.0 version that was just released? I installed from Google Play and didn't see it listed anyway, but I am probably overlooking it. Is it turned on by default?

**Comment by iNPUTmice** [comment]
@deoren No you will have to compile Conversations yourself. There is no UI setting for this. Just the hard coded Config.java variable.

**Comment by Natureshadow** [comment]
I have to report that the issue still appears with ejabberd. It was just quiet for two days, but now we are back to the full storm of old messages.

**Comment by deoren** [comment]
@iNPUTmice thanks for clarifying. Any plans to add a toggle within the UI, perhaps under `Settings > Expert options`?

**Comment by mwild1** [comment]
Hi Prosody-using folks. We just pushed some updates to mod_smacks in the prosody-modules repository. To update, run: hg pull -u -R /path/to/prosody-modules and restart Prosody.

A reminder for future reports (even if you have already commented) please say what version of Conversations, Prosody and mod_smacks you are using (you can find the last one with the command: hg id /path/to/prosody-modules ).

I'm interested to know if the update changes the behaviour in any way for people experiencing the issue.

@iNPUTmice You don't experience the issue - what version of mod_smacks do you have? (see command above)

**Comment by mgansler** [comment]
I have updated my docker image:
docker pull mgansler/prosody:nightly
prosody nightly 132, community modules from right after the post above :)

**Comment by devurandom** [comment]
@mgansler Maybe you can embed the version information into the Docker image tag or make it otherwise available?

**Comment by mgansler** [comment]
mgansler/prosody:0.10-132_e4867211cddb

**Comment by mgansler** [comment]
I worked on my docker images a bit:
mgansler/prosody:nightly-0.10-131 has only prosody installed
mgansler/prosody-modules:e4867211cddb contains the current modules
This way, modules and prosody itself can be updated individually.
See [docker-prosody-modules](https://github.com/mgansler/docker-prosody-modules) for hints on how to combine the two containers.
I will continue to tag all kinds of different versions of prosody and/or the modules, i hope it helps debugging.

**Comment by deoren** [comment]
@mwild1 It may be too soon to tell, but I've not noticed any duplicate messages since upgrading to `1706:e4867211cdd` of the prosody modules repo and restarting Prosody.

**Comment by kriztan** [comment]
@mwild1 I'm using mod_smacks `e4867211cddb` with prosody-trunk `561` and Conversations 1.4.0 alpha for 2 days. Now I've noticed that there were still some duplicates, but less than before and in the logfiles are still lines like that `The client says it handled 130 new stanzas, but we only sent 122 :)`.

Please tell me, how to help with that.

**Comment by mwild1** [comment]
@kriztan Any chance you could email some debug logs to matthew@prosody.im?

**Comment by arty-name** [comment]
Using Conversations 1.4.3, Prosody 0.10 1nightly139-1~trusty, mod_smacks 1733:9abd3dce619a I do not seem to get duplicates

**Comment by mwild1** [comment]
Anyone else still experiencing this issue on the updated versions?

**Comment by mase76** [comment]
I did not get any duplicate messages within the last weeks. Prosody and mod_smacks was kept up to date all the time.

**Comment by iNPUTmice** [comment]
Ok I'm closing here since this probably resolved and didn't seem to be a Conversations problem anyway.
